### ISSUE TITLE
Error: no such bucket

### ISSUE THREAD

**Issue by rblakeley** [awslabs/aws-nodejs-sample#3]
I followed the instructions for getting started and encountered this error. I clean out and started over twice and got the same error:  
```
> node sample
> { [NoSuchBucket: The specified bucket does not exist]
  message: 'The specified bucket does not exist',
  code: 'NoSuchBucket',
  region: null,
  time: Sat Feb 27 2016 14:41:23 GMT-0700 (MST),
  requestId: 'AC47248A27D24E87',
  extendedRequestId: 'DcHPnnYuP8MYBB+u5sKUSdGzNh1hmA4G0Cv39Lz9CDugdtaNg0TwnU+IOfAoxyy6bhX6l//c3ic=',
  statusCode: 404,
  retryable: false,
  retryDelay: 18.96829721517861 }
```

**Comment by rblakeley** [comment]
This was a permissions issue. Not a big fan of the error message.

For anyone else getting started, you have to set up a policy on your user. IAM Management Console -> Users -> Click user -> Permissions -> Attach Policy -> Administrator Access (or pick one that fits your case)

**Comment by BrunoCode** [comment]
Thank you that was my problem and solution.
