### ISSUE TITLE
InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.

### ISSUE THREAD

**Issue by leochu** [awslabs/aws-nodejs-sample#9]
Hi, 

I followed the instructions on your Git page and ran into this issue. I've verified the access-key-id and I've tried recreating the set (access-key id and secret key) a couple of times. 

I did an npm install and added my credentials to the ~/.aws/credentials file on MacOS. 

Can you provide some kind of trouble-shooting steps ?

**Comment by clockworked247** [comment]
@leochu I agree, steps for debugging would be most helpful.  The error message give no information regarding what the key is, so it's hard to tell what might have gone wrong.  I also ensured my ~/.aws/credentials were correct and cleared out any old environment variables in my ~/.bash_profile and even flushed DNS cache.   Nothing fixed the issue.
